In [27]:
!pip install cloud-tpu-client==0.10 torch==2.0.0  torchvision==0.15.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [28]:
import torch 


In [29]:
torch.__version__

'2.0.0+cu118'

In [30]:
 import numpy as np
 import pandas as pd
 import seaborn
 import matplotlib.pyplot as plt

In [31]:
lst = np.array([1, 2, 3 ,4])
lst.dtype

dtype('int64')

In [32]:
tensors = torch.from_numpy(lst) # Convert numpy to PyTorch tensors
tensors

tensor([1, 2, 3, 4])

In [33]:
data = [[1,2] , [3,4]]
x_data = torch.tensor(data)

In [34]:
x_data.dtype

torch.int64

**Creating from another Tensor**

In [35]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: {x_ones} \n")

Ones Tensor: tensor([[1, 1],
        [1, 1]]) 



In [36]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random Tensor: {x_rand}")

Random Tensor: tensor([[0.3454, 0.0401],
        [0.4889, 0.2180]])


**Tensor with random or constant values:**

```shape```
 is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor.

In [37]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [38]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7891, 0.1711, 0.5974],
        [0.7469, 0.1583, 0.6264]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [40]:
rand_tensor.shape

torch.Size([2, 3])

**Tensor Attributes**

Tensor attributes describe their shape, datatype, and the device on which they are stored.

In [41]:
tensor =  torch.rand(2,2)

In [42]:
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


**Tensor Operations**

Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random sampling, and more are comprehensively described here.

In [45]:
t1 = torch.tensor([[2,3,4] , [1, 2, 3]])
t2 =  torch.tensor([[1,2] , [2 ,3] , [3,4]])
t3 = torch.ones(t1.shape)
print(t1 @ t2)

tensor([[20, 29],
        [14, 20]])


In [48]:
print(f"Sum of T1 and T3 tensor :\n {t1 + t3}")

Sum of T1 and T3 tensor :
 tensor([[3., 4., 5.],
        [2., 3., 4.]])


In [50]:
torch.add(t1 , t3)

tensor([[3., 4., 5.],
        [2., 3., 4.]])

In [53]:
c = torch.zeros(t1.shape)
torch.add(t1 , t3 , out = c)
print(c)

tensor([[3., 4., 5.],
        [2., 3., 4.]])


In [54]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [56]:
sum = torch.add(a,b).sum()
print(sum)

tensor(27.)


**Dot Products and Mult Operations**

In [57]:
torch.mul(a ,b)

tensor([12., 20., 30.])

In [59]:
torch.matmul(t1,t2)

tensor([[20, 29],
        [14, 20]])

In [61]:
a.dot(b) # erformig dot roduct

tensor(62.)